services:
  - type: web
    name: google-ads-report
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: google-ads-report
          property: url
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_ADS_CUSTOMER_ID
        sync: false  
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        sync: false
      - key: GOOGLE_ADS_LOGIN_CUSTOMER_ID
        sync: false
      - key: GOOGLE_ADS_REFRESH_TOKEN
        sync: false
      - key: USE_REAL_API
        value: "true" 